app_servers = {
    # :lvs1 => '192.168.33.20',
    # :lvs2 => '192.168.33.21',
    :web1 => '192.168.33.30',
    # :web2 => '192.168.33.31',
}

Vagrant.configure("2") do |config|
    config.vm.box = "common_dev_1"

    app_servers.each do |app_server_name, app_server_ip|
        config.vm.define app_server_name do |app_config|
            app_config.vm.hostname = "#{app_server_name.to_s}.vagrant.internal"
            app_config.vm.provision :shell, path: "bootstrap.sh"
            app_config.vm.network :private_network, ip: app_server_ip
            app_config.vm.synced_folder "www", "/home/www"
            app_config.vm.provider "virtualbox" do |vb|
                vb.name = app_server_name.to_s
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
                vb.customize ["modifyvm", :id, "--memory", "1100"]
                vb.customize ["modifyvm", :id, "--cpus", "2"]
                vb.cpus = 2
            end
        end
    end
end